/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica12;

import SM.RRA.IU.Lienzo2D;
import SM.RRA.IU.MiManejadorLienzo;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.DefaultListModel;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author raul
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {

    MiManejadorLienzo manejador;

    /**
     * Este es el constructor de la clase VentanaInternaImagen que crea una
     * nueva instancia de la ventana interna para mostrar una imagen. Realiza
     * varias configuraciones iniciales y asigna un MiManejadorLienzo a la
     * ventana interna.
     */
    public VentanaInternaImagen() {
        initComponents();
        this.setSize(500, 500);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setResizable(true);

        manejador = new MiManejadorLienzo();
        this.getLienzo2D().addLienzoListener(manejador);
    }

    /**
     * Getter de lienzo
     *
     * @return Lienzo2D
     */
    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D = new SM.RRA.IU.Lienzo2D();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private SM.RRA.IU.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
