/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica12;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 *
 * @author raul
 */
public class VentanaInternaCamara extends javax.swing.JInternalFrame {

    private Webcam camara = null;

    /**
     * Constructor privado que inicializa una instancia de la clase
     * VentanaInternaCamara. Configura los componentes gráficos, establece el
     * tamaño de la ventana, obtiene la cámara predeterminada, ajusta la
     * resolución de visualización y agrega el panel de visualización al
     * contenido principal de la ventana interna.
     */
    private VentanaInternaCamara() {
        initComponents();
        this.setSize(100, 100);
        camara = Webcam.getDefault();
        if (camara != null) {
            Dimension resoluciones[] = camara.getViewSizes();
            Dimension maxRes = resoluciones[resoluciones.length - 1];
            camara.setViewSize(maxRes);
            WebcamPanel areaVisual = new WebcamPanel(camara);
            if (areaVisual != null) {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
    }

    /**
     * Este método estático devuelve una instancia de la clase
     * VentanaInternaCamara. Si la variable camara de la instancia v no es nula,
     * se devuelve la instancia v. De lo contrario, se devuelve null.
     *
     * Parámetros:
     *
     * Este método no acepta ningún parámetro.
     *
     * Valor de retorno:
     *
     * VentanaInternaCamara - una instancia de la clase VentanaInternaCamara si
     * v.camara no es nula. null - si v.camara es nula.
     *
     * @return
     */
    public static VentanaInternaCamara getInstance() {
        VentanaInternaCamara v = new VentanaInternaCamara();
        return (v.camara != null ? v : null);
    }

    /**
     * Este método devuelve una imagen capturada por la cámara (camara) como un
     * objeto BufferedImage. Si camara no es nula, se llama al método getImage()
     * de la cámara y se devuelve la imagen resultante. De lo contrario, se
     * devuelve null.
     *
     * Parámetros:
     *
     * Este método no acepta ningún parámetro.
     *
     * Valor de retorno:
     *
     * @return BufferedImage - la imagen capturada por la cámara (camara) si
     * camara no es nula. null - si camara es nula.
     *
     *
     */
    public BufferedImage getImage() {
        return camara != null ? camara.getImage() : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método es invocado cuando se cierra un marco interno en una
     * aplicación de interfaz gráfica de usuario (GUI) construida con Swing. El
     * método maneja el evento de cierre del marco interno.
     *
     *
     *
     * @param evt (javax.swing.event.InternalFrameEvent): El evento de cierre
     * del marco interno que desencadena la ejecución del método.
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (camara != null) {
            camara.close();
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
