package practica10;

import SM.RRA.IU.Lienzo2D;
import SM.RRA.IU.LienzoAdapter;
import SM.RRA.IU.LienzoEvent;
import SM.RRA.IU.tipos;
import javax.swing.JFileChooser;
import java.awt.*;
import java.awt.color.ColorSpace;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.geom.AffineTransform;
import java.awt.geom.Line2D;
import java.awt.image.AffineTransformOp;
import java.awt.image.BandCombineOp;
import java.awt.image.BufferedImage;
import java.awt.image.ByteLookupTable;
import java.awt.image.ColorConvertOp;
import java.awt.image.ColorModel;
import java.awt.image.ComponentColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.DataBuffer;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.tools.JavaFileManager;
import sm.image.KernelProducer;
import sm.image.LookupTableProducer;

/**
 *
 * @author raul
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private BufferedImage imgFuente = null;

    /**
     * Creates new form VentanaPrincipal Titulo y tamaño personalizados
     */
    public VentanaPrincipal() {
        this.setTitle("PAINT BASICO");
        this.setSize(2000, 2000);
        initComponents();
        listaLateral.setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barraEstado2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        brillo = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        Contraste = new javax.swing.JSlider();
        filtro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contrasteBoton = new javax.swing.JButton();
        iluminada = new javax.swing.JButton();
        oscurecer = new javax.swing.JButton();
        slider2 = new javax.swing.JSlider();
        slider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        rotar = new javax.swing.JButton();
        aumento = new javax.swing.JButton();
        disminucion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cuadratica = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cambioEspColor = new javax.swing.JComboBox<>();
        muestraBanda = new javax.swing.JButton();
        lineal = new javax.swing.JToggleButton();
        combiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        abrir = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        dibujoLibre = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        cuadrado = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        curva = new javax.swing.JToggleButton();
        smile = new javax.swing.JToggleButton();
        seleccion = new javax.swing.JToggleButton();
        colores1 = new javax.swing.JPanel();
        negro1 = new javax.swing.JToggleButton();
        rojo1 = new javax.swing.JToggleButton();
        azul1 = new javax.swing.JToggleButton();
        amarillo1 = new javax.swing.JToggleButton();
        verde1 = new javax.swing.JToggleButton();
        masColores = new javax.swing.JToggleButton();
        relleno2 = new javax.swing.JCheckBox();
        transparencia = new javax.swing.JToggleButton();
        alisar = new javax.swing.JToggleButton();
        spinner = new javax.swing.JSpinner();
        volcar = new javax.swing.JToggleButton();
        panelDividido = new javax.swing.JSplitPane();
        escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaLateral = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        menuNuevo = new javax.swing.JMenuItem();
        Imagen = new javax.swing.JMenu();
        abreImagen = new javax.swing.JMenuItem();
        reescalado = new javax.swing.JMenuItem();
        convolucion = new javax.swing.JMenuItem();
        affineTransform = new javax.swing.JMenuItem();
        lookUpOp = new javax.swing.JMenuItem();
        BandCombineOp = new javax.swing.JMenuItem();
        colorConvertOp = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        barraEstado = new javax.swing.JCheckBoxMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        barraEstado2.setBackground(new java.awt.Color(153, 153, 153));
        barraEstado2.setText("Barra de Estado");
        jPanel2.add(barraEstado2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(1183, 100));

        brillo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        brillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brilloStateChanged(evt);
            }
        });
        brillo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                brilloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                brilloFocusLost(evt);
            }
        });

        jLabel2.setText("Brillo Y Contraste");

        Contraste.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Contraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContrasteStateChanged(evt);
            }
        });
        Contraste.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContrasteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContrasteFocusLost(evt);
            }
        });

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Binomial", "Enfoque", "Relive", "Laplaciano", "Horizontal" }));
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });

        jLabel3.setText("Filtro");

        contrasteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/contraste.png"))); // NOI18N
        contrasteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasteBotonActionPerformed(evt);
            }
        });

        iluminada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/iluminar.png"))); // NOI18N
        iluminada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iluminadaActionPerformed(evt);
            }
        });

        oscurecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/oscurecer.png"))); // NOI18N
        oscurecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oscurecerActionPerformed(evt);
            }
        });

        slider2.setMaximum(255);
        slider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider2StateChanged(evt);
            }
        });
        slider2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                slider2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                slider2FocusLost(evt);
            }
        });

        slider1.setMaximum(255);
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });
        slider1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                slider1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                slider1FocusLost(evt);
            }
        });

        jLabel4.setText("Transformaciones");

        rotar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/rotacion180.png"))); // NOI18N
        rotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarActionPerformed(evt);
            }
        });

        aumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/aumentar.png"))); // NOI18N
        aumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentoActionPerformed(evt);
            }
        });

        disminucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/disminuir.png"))); // NOI18N
        disminucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminucionActionPerformed(evt);
            }
        });

        jLabel5.setText("Rotación Y escalado");

        cuadratica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/cuadratica.png"))); // NOI18N
        cuadratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadraticaActionPerformed(evt);
            }
        });

        jLabel6.setText("Color");

        cambioEspColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sRGB", "YCC", "GREY" }));
        cambioEspColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioEspColorActionPerformed(evt);
            }
        });

        muestraBanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/bandas.png"))); // NOI18N
        muestraBanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muestraBandaActionPerformed(evt);
            }
        });

        lineal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/lineal.png"))); // NOI18N
        lineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linealActionPerformed(evt);
            }
        });

        combiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/combinar.png"))); // NOI18N
        combiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(brillo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(contrasteBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iluminada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oscurecer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadratica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lineal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disminucion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(muestraBanda)
                        .addGap(24, 24, 24)
                        .addComponent(cambioEspColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combiar))
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filtro)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(brillo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Contraste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(slider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aumento)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuadratica)
                                    .addComponent(contrasteBoton)
                                    .addComponent(iluminada)
                                    .addComponent(oscurecer)
                                    .addComponent(lineal))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(rotar)
                                    .addGap(10, 10, 10)))
                            .addComponent(disminucion)
                            .addComponent(muestraBanda)
                            .addComponent(cambioEspColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combiar))
                        .addGap(28, 28, 28))))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setMaximumSize(new java.awt.Dimension(31, 31));
        jPanel1.setMinimumSize(new java.awt.Dimension(29, 29));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/abrir.png"))); // NOI18N
        abrir.setFocusable(false);
        abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jToolBar1.add(abrir);

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/nuevo.png"))); // NOI18N
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevo);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/guardar.png"))); // NOI18N
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jToolBar1.add(guardar);

        buttonGroup1.add(dibujoLibre);
        dibujoLibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/trazo.png"))); // NOI18N
        dibujoLibre.setFocusable(false);
        dibujoLibre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dibujoLibre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dibujoLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujoLibreActionPerformed(evt);
            }
        });
        jToolBar1.add(dibujoLibre);

        buttonGroup1.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/linea.png"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        jToolBar1.add(linea);

        buttonGroup1.add(cuadrado);
        cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/rectangulo.png"))); // NOI18N
        cuadrado.setFocusable(false);
        cuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadrado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoActionPerformed(evt);
            }
        });
        jToolBar1.add(cuadrado);

        buttonGroup1.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/elipse.png"))); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        jToolBar1.add(elipse);

        buttonGroup1.add(curva);
        curva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/curva.png"))); // NOI18N
        curva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        curva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        curva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvaActionPerformed(evt);
            }
        });
        jToolBar1.add(curva);

        buttonGroup1.add(smile);
        smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/smile.png"))); // NOI18N
        smile.setFocusable(false);
        smile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        smile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smileActionPerformed(evt);
            }
        });
        jToolBar1.add(smile);

        seleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/seleccion.png"))); // NOI18N
        seleccion.setFocusable(false);
        seleccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seleccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });
        jToolBar1.add(seleccion);

        colores1.setPreferredSize(new java.awt.Dimension(35, 25));
        colores1.setLayout(new java.awt.GridLayout(2, 3));

        negro1.setBackground(new java.awt.Color(0, 0, 0));
        negro1.setPreferredSize(new java.awt.Dimension(25, 25));
        negro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro1ActionPerformed(evt);
            }
        });
        colores1.add(negro1);

        rojo1.setBackground(new java.awt.Color(255, 0, 0));
        rojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo1ActionPerformed(evt);
            }
        });
        colores1.add(rojo1);

        azul1.setBackground(new java.awt.Color(0, 0, 204));
        azul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul1ActionPerformed(evt);
            }
        });
        colores1.add(azul1);

        amarillo1.setBackground(new java.awt.Color(255, 255, 51));
        amarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo1ActionPerformed(evt);
            }
        });
        colores1.add(amarillo1);

        verde1.setBackground(new java.awt.Color(51, 255, 51));
        verde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde1ActionPerformed(evt);
            }
        });
        colores1.add(verde1);

        masColores.setText("+");
        masColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masColoresActionPerformed(evt);
            }
        });
        colores1.add(masColores);

        jToolBar1.add(colores1);

        relleno2.setBackground(new java.awt.Color(102, 255, 204));
        relleno2.setFocusable(false);
        relleno2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        relleno2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/rellenar.png"))); // NOI18N
        relleno2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        relleno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relleno2ActionPerformed(evt);
            }
        });
        jToolBar1.add(relleno2);

        transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/transparencia.png"))); // NOI18N
        transparencia.setFocusable(false);
        transparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(transparencia);

        alisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/alisar.png"))); // NOI18N
        alisar.setFocusable(false);
        alisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisarActionPerformed(evt);
            }
        });
        jToolBar1.add(alisar);

        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });
        jToolBar1.add(spinner);

        volcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/volcar.png"))); // NOI18N
        volcar.setFocusable(false);
        volcar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        volcar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(volcar);

        jPanel5.add(jToolBar1);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelDividido.setDividerLocation(1050);

        escritorio.setPreferredSize(new java.awt.Dimension(1050, 651));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        panelDividido.setLeftComponent(escritorio);

        jScrollPane1.setViewportView(listaLateral);

        panelDividido.setRightComponent(jScrollPane1);

        getContentPane().add(panelDividido, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        Archivo.setText("Archivo");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);
        Archivo.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        menuNuevo.setText("Nuevo Lienzo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        Archivo.add(menuNuevo);

        jMenuBar1.add(Archivo);

        Imagen.setText("Imagen");

        abreImagen.setText("Abrir imagen");
        abreImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abreImagenActionPerformed(evt);
            }
        });
        Imagen.add(abreImagen);

        reescalado.setText("Reescalado");
        reescalado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reescaladoActionPerformed(evt);
            }
        });
        Imagen.add(reescalado);

        convolucion.setText("Convolución");
        convolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convolucionActionPerformed(evt);
            }
        });
        Imagen.add(convolucion);

        affineTransform.setText("AffineTransform");
        affineTransform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affineTransformActionPerformed(evt);
            }
        });
        Imagen.add(affineTransform);

        lookUpOp.setText("LookUpOp");
        lookUpOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookUpOpActionPerformed(evt);
            }
        });
        Imagen.add(lookUpOp);

        BandCombineOp.setText("BandCombineOp");
        BandCombineOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandCombineOpActionPerformed(evt);
            }
        });
        Imagen.add(BandCombineOp);

        colorConvertOp.setText("ColorConvertOp");
        colorConvertOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorConvertOpActionPerformed(evt);
            }
        });
        Imagen.add(colorConvertOp);

        jMenuBar1.add(Imagen);

        Edicion.setText("Edicion");

        barraEstado.setSelected(true);
        barraEstado.setText("Ver barra de estado");
        barraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEstadoActionPerformed(evt);
            }
        });
        Edicion.add(barraEstado);

        jMenuBar1.add(Edicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEstadoActionPerformed
        this.barraEstado2.setVisible(barraEstado.isSelected());
    }//GEN-LAST:event_barraEstadoActionPerformed

    /**
     * Muestra diálogo de abrir.
     */
    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().addLienzoListener(new ManejadorLienzo());
                vi.addInternalFrameListener(new ManejadorVentanaInterna());
                vi.getLienzo2D().setImagen(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);

            } catch (Exception ex) {
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    /**
     * Cierra la aplicación.
     */
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @brief Pulsando nuevo borramos todos los dibujos. Invoca el método
     * nuevoLienzo de la clase lienzo que se encarga de "borrar".
     */
    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        this.getLienzoSeleccionado().nuevoLienzo();
    }//GEN-LAST:event_NuevoActionPerformed

    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.ELIPSE);
            barraEstado2.setText("Elipse");
        }
    }//GEN-LAST:event_elipseActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.LINEA);
            barraEstado2.setText("Línea");
        }
    }//GEN-LAST:event_lineaActionPerformed

    private void cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.RECTANGULO);
            barraEstado2.setText("Rectángulo");
        }
    }//GEN-LAST:event_cuadradoActionPerformed
//*******************************************************************************//

    /**
     * Dialogo de guardar.
     *
     * @param evt
     */
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen(true);
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                        System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img = new BufferedImage(300, 300, BufferedImage.TYPE_INT_ARGB);
        vi.getLienzo2D().setImagen(img);
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void negro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro1ActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setColor(Color.black);
        }
    }//GEN-LAST:event_negro1ActionPerformed

    private void rojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo1ActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setColor(Color.red);
        }
    }//GEN-LAST:event_rojo1ActionPerformed

    private void azul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul1ActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setColor(Color.blue);
        }
    }//GEN-LAST:event_azul1ActionPerformed

    private void amarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo1ActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setColor(Color.yellow);
        }
    }//GEN-LAST:event_amarillo1ActionPerformed

    private void verde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde1ActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setColor(Color.green);
        }
    }//GEN-LAST:event_verde1ActionPerformed

    private void relleno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relleno2ActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setRelleno(relleno2.isSelected());
        }
        }//GEN-LAST:event_relleno2ActionPerformed

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setMover(seleccion.isSelected());
        }
       }//GEN-LAST:event_seleccionActionPerformed

    private void masColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masColoresActionPerformed
        if (hayLienzo()) {
            Color color = JColorChooser.showDialog(this, "Elija un color", Color.red);
            this.getLienzoSeleccionado().setColor(color);
        }
    }//GEN-LAST:event_masColoresActionPerformed

    private void curvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvaActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.CURVA);
        }
        barraEstado2.setText("Curva");
    }//GEN-LAST:event_curvaActionPerformed

    /**
     * @brief Creamos una ventana interna que se añade a nuestro escritorio y
     * creamos una imagen vacía en blanco.
     * @param evt el evento
     */
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        vi.getLienzo2D().addLienzoListener(new ManejadorLienzo());
        vi.addInternalFrameListener(new ManejadorVentanaInterna());
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img;
        img = new BufferedImage(800, 800, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, img.getWidth(), img.getHeight());
        vi.getLienzo2D().setImagen(img);

    }//GEN-LAST:event_nuevoActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImagen(img);
                vi.setTitle(f.getName()); // Agregar esta línea para establecer el título de la ventana interna
                this.escritorio.add(vi);
                vi.setVisible(true);
                vi.getLienzo2D().addLienzoListener(new ManejadorLienzo());
                vi.addInternalFrameListener(new ManejadorVentanaInterna());
            } catch (Exception ex) {
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen(true);
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "png", f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                        System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void smileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smileActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.SMILE);
        }
        barraEstado2.setText("Smile");
    }//GEN-LAST:event_smileActionPerformed

    private void abreImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreImagenActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImagen(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            } catch (Exception ex) {
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_abreImagenActionPerformed

    private void dibujoLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujoLibreActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.LIBRE);
        }
        barraEstado2.setText("Trazo libre");
    }//GEN-LAST:event_dibujoLibreActionPerformed

    private void transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTransparente(transparencia.isSelected());
        }
    }//GEN-LAST:event_transparenciaActionPerformed

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setGrosor(Integer.parseInt(spinner.getValue().toString()));
        }
    }//GEN-LAST:event_spinnerStateChanged

    private void alisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisarActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setLiso(alisar.isSelected());
        }
    }//GEN-LAST:event_alisarActionPerformed

    private void reescaladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reescaladoActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    RescaleOp rop = new RescaleOp(1.0F, 100.0F, null);
                    rop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_reescaladoActionPerformed

    private void convolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convolucionActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    float filtro[] = {0.1f, 0.1f, 0.1f, 0.1f, 0.2f, 0.1f, 0.1f, 0.1f, 0.1f};
                    Kernel k = new Kernel(3, 3, filtro);
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_convolucionActionPerformed

    private void brilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brilloStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgFuente != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    int brillo = this.brillo.getValue();
                    RescaleOp rop = new RescaleOp(1.0F, brillo, null);
                    rop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_brilloStateChanged

    private void ContrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContrasteStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgFuente != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    float c = ((float) this.Contraste.getValue() / 100.0f);
                    RescaleOp rop = new RescaleOp(c, 0, null);
                    rop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ContrasteStateChanged

    private void brilloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brilloFocusGained
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            ColorModel cm = vi.getLienzo2D().getImagen().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImagen().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImagen().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_brilloFocusGained

    private void brilloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brilloFocusLost
        imgFuente = null;
        this.brillo.setValue(0);
    }//GEN-LAST:event_brilloFocusLost

    private void ContrasteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContrasteFocusGained
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            ColorModel cm = vi.getLienzo2D().getImagen().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImagen().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImagen().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_ContrasteFocusGained

    private Kernel getKernel(int seleccion) {
        Kernel k = null;
        float filtro[] = null;
        switch (seleccion) {
            case 0:
                filtro = KernelProducer.MASCARA_MEDIA_3x3;
                k = new Kernel(3, 3, filtro);
                break;
            case 1:
                filtro = KernelProducer.MASCARA_BINOMIAL_3x3;
                k = new Kernel(3, 3, filtro);
                break;
            case 2:
                filtro = KernelProducer.MASCARA_ENFOQUE_3x3;
                k = new Kernel(3, 3, filtro);
                break;
            case 3:
                filtro = KernelProducer.MASCARA_RELIEVE_3x3;
                k = new Kernel(3, 3, filtro);
                break;
            case 4:
                filtro = KernelProducer.MASCARA_LAPLACIANA_3x3;
                k = new Kernel(3, 3, filtro);
                break;
            case 5:
                filtro = new float[]{0.2f, 0.2f, 0.2f, 0.2f, 0.2f};
                k = new Kernel(1, 5, filtro);
                break;

        }
        return k;
    }

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            int seleccion = this.filtro.getSelectedIndex();
            Kernel k = getKernel(seleccion);
            if (img != null && k != null) {
                try {
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_filtroActionPerformed

    private void ContrasteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContrasteFocusLost
        imgFuente = null;
        this.Contraste.setValue(0);
    }//GEN-LAST:event_ContrasteFocusLost

    private void lookUpOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    byte funcionT[] = new byte[256];
                    for (int x = 0; x < 256; x++) {
                        funcionT[x] = (byte) (255 - x); // Negativo
                    }
                    LookupTable tabla = new ByteLookupTable(0, funcionT);
                    LookupOp lop = new LookupOp(tabla, null);
                    BufferedImage imgdest = lop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_lookUpOpActionPerformed

    private void affineTransformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affineTransformActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getScaleInstance(1.5, 1.5);
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_affineTransformActionPerformed

    private void contrasteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasteBotonActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    int type = LookupTableProducer.TYPE_SFUNCION;
                    LookupTable lt = LookupTableProducer.createLookupTable(type);
                    LookupOp lop = new LookupOp(lt, null);
                    lop.filter(img, img); // Imagen origen y destino iguales
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_contrasteBotonActionPerformed

    private static LookupTable createLogarithmicLookupTable(double factorContraste, double factorIluminacion) {
        double gamma = 1.0 / factorContraste;
        byte[] lutData = new byte[256];
        for (int i = 0; i < lutData.length; i++) {
            double value = 255.0 * Math.pow((double) i / 255.0, gamma) + (factorIluminacion - 0.5) * 255.0;
            lutData[i] = (byte) (value + 0.5);
        }
        return new ByteLookupTable(0, lutData);
    }


    private void iluminadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iluminadaActionPerformed
        /*VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    // Ajuste de contraste con iluminación utilizando función logarítmica
                    double a = 255.0 / Math.log(256);
                    double b = 255.0 / Math.log(1.0 + a);
                    LookupTable lt = createLogarithmicLookupTable(a, b);
                    LookupOp lop = new LookupOp(lt, null);
                    lop.filter(img, img); // Imagen origen y destino iguales
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }*/
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    LookupTable lt = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_GAMMA_CORRECTION);
                    LookupOp lop = new LookupOp(lt, null);
                    lop.filter(img, img); // Imagen origen y destino iguales
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_iluminadaActionPerformed

    private void oscurecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oscurecerActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    LookupTable lt = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_POWER);
                    LookupOp lop = new LookupOp(lt, null);
                    lop.filter(img, img); // Imagen origen y destino iguales
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_oscurecerActionPerformed


    private void rotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getRotateInstance(Math.toRadians(180), img.getWidth() / 2, img.getHeight() / 2);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at, null);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_rotarActionPerformed

    private void BandCombineOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandCombineOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    float[][] matriz = {
                        {0.0F, 0.5F, 0.5F},
                        {0.5F, 0.0F, 0.5F},
                        {0.5F, 0.5F, 0.0F}
                    };
                    BandCombineOp bcop = new BandCombineOp(matriz, null);
                    bcop.filter(img.getRaster(), img.getRaster());
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_BandCombineOpActionPerformed

    private void colorConvertOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorConvertOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                    ColorConvertOp op = new ColorConvertOp(cs, null);
                    BufferedImage imgdest = op.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_colorConvertOpActionPerformed

    private void aumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentoActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getScaleInstance(1.25, 1.25);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at, null);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_aumentoActionPerformed

    private void disminucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminucionActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getScaleInstance(0.75, 0.75);
                    AffineTransformOp atop;
                    atop = new AffineTransformOp(at, null);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImagen(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_disminucionActionPerformed

    private LookupOp linealConInflexion(double a, double b) {
        final int valorMax = 255;
        final int valorMin = 0;

        double m = 0;
        if (a != valorMax) {
            m = (valorMax - b) / (valorMax - a);
        }

        byte funcionL[] = new byte[256];
        for (int x = 0; x < 256; ++x) {
            if (x < a) {
                funcionL[x] = (byte) ((b / a) * x);
            }
            if (x >= a) {
                funcionL[x] = (byte) (m * (x - a) + b);
            }
        }
        LookupTable tabla = new ByteLookupTable(0, funcionL);
        return new LookupOp(tabla, null);
    }


    private void linealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linealActionPerformed
        if (lineal.isSelected()) {
            slider1.setEnabled(true);
            slider2.setEnabled(true);
        }

        if (!lineal.isSelected()) {
            slider1.setEnabled(false);
            slider2.setEnabled(false);
        }
    }//GEN-LAST:event_linealActionPerformed

    /**
     * Función cuadrática f(x) = 1/100(x-m)² siendo 0 <= m <= 255
     *
     * @param m
     * @return
     */
    private LookupTable cuadratica(double m) {
        double k = 100.0 * 255.0;
        byte[] data = new byte[256];
        for (int i = 0; i < 256; i++) {
            int v = (int) (((i - m) * (i - m) / k) * 255.0);
            if (v < 0) {
                v = 0;
            }
            if (v > 255) {
                v = 255;
            }
            data[i] = (byte) v;
        }
        return new ByteLookupTable(0, data);
    }


    private void cuadraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadraticaActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    double m = 128.0;
                    LookupTable lt = cuadratica(m);
                    LookupOp lop = new LookupOp(lt, null);
                    lop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch (Exception e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_cuadraticaActionPerformed

    private BufferedImage getImageBand(BufferedImage img, int banda) {
        //Creamos el modelo de color de la nueva imagen basado en un espcio de color GRAY
        ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
        ComponentColorModel cm = new ComponentColorModel(cs, false, false,
                Transparency.OPAQUE,
                DataBuffer.TYPE_BYTE);
        //Creamos el nuevo raster a partir del raster de la imagen original
        int vband[] = {banda};
        WritableRaster bRaster = (WritableRaster) img.getRaster().createWritableChild(0, 0,
                img.getWidth(), img.getHeight(), 0, 0, vband);
        //Creamos una nueva imagen que contiene como raster el correspondiente a la banda
        return new BufferedImage(cm, bRaster, false, null);
    }


    private void muestraBandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muestraBandaActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    for (int i = 0; i < img.getRaster().getNumBands(); ++i) {
                        BufferedImage imgBanda = getImageBand(img, i);
                        vi = new VentanaInterna();
                        vi.getLienzo2D().setImagen(imgBanda);
                        escritorio.add(vi);
                        vi.setVisible(true);
                    }
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_muestraBandaActionPerformed

    //TODO
    private void cambioEspColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioEspColorActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                ColorSpace cs = null;
                int seleccion = this.cambioEspColor.getSelectedIndex();
                switch (seleccion) {
                    default:
                        break;
                    case 0:
                        cs = ColorSpace.getInstance(ColorSpace.CS_sRGB);
                        break;
                    case 1:
                        cs = ColorSpace.getInstance(ColorSpace.CS_PYCC);
                        break;
                    case 2:
                        cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                        break;

                }
                try {
                    ColorConvertOp op = new ColorConvertOp(cs, null);
                    BufferedImage imgdest = op.filter(img, null);
                    vi = new VentanaInterna();
                    vi.getLienzo2D().setImagen(imgdest);
                    escritorio.add(vi);
                    vi.setVisible(true);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_cambioEspColorActionPerformed

    private void combiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combiarActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();

            if (img != null) {
                try {
                    float[][] matriz = {
                        {0.0F, 0.5F, 0.5F},
                        {0.5F, 0.0F, 0.5F},
                        {0.5F, 0.5F, 0.0F}
                    };
                    BandCombineOp bcop = new BandCombineOp(matriz, null);
                    bcop.filter(img.getRaster(), img.getRaster());
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_combiarActionPerformed


    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    LookupOp lop = linealConInflexion(slider1.getValue(), slider2.getValue());
                    lop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
        System.out.println("v1 cambia");
    }//GEN-LAST:event_slider1StateChanged

    private void slider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider2StateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen();
            if (img != null) {
                try {
                    LookupOp lop = linealConInflexion(slider1.getValue(), slider2.getValue());
                    lop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
        System.out.println("v2 cambia");
    }//GEN-LAST:event_slider2StateChanged


    private void slider1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_slider1FocusGained
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            ColorModel cm = vi.getLienzo2D().getImagen().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImagen().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImagen().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_slider1FocusGained

    private void slider1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_slider1FocusLost
        imgFuente = null;
    }//GEN-LAST:event_slider1FocusLost

    private void slider2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_slider2FocusGained
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            ColorModel cm = vi.getLienzo2D().getImagen().getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImagen().copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImagen().isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_slider2FocusGained

    private void slider2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_slider2FocusLost
        imgFuente = null;
    }//GEN-LAST:event_slider2FocusLost

    Lienzo2D getLienzoSeleccionado() {
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        return vi != null ? vi.getLienzo2D() : null;
    }

    boolean hayLienzo() {
        return this.getLienzoSeleccionado() != null;
    }

    public class ManejadorLienzo extends LienzoAdapter {

        public void shapeAdded(LienzoEvent evt) {
            Shape s = evt.getForma();
            ((DefaultListModel) listaLateral.getModel()).addElement(s);
        }
    }

    public class ManejadorVentanaInterna extends InternalFrameAdapter {

        public void internalFrameActivated(InternalFrameEvent evt) {
            VentanaInterna vi = (VentanaInterna) evt.getInternalFrame();
            DefaultListModel modelo = new DefaultListModel();
            modelo.addAll(vi.getLienzo2D().getShapeList());
            listaLateral.setModel(modelo);
        }

        public void internalFrameClosing(InternalFrameEvent evt) {
            ((DefaultListModel) listaLateral.getModel()).removeAllElements();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem BandCombineOp;
    private javax.swing.JSlider Contraste;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenu Imagen;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem abreImagen;
    private javax.swing.JButton abrir;
    private javax.swing.JMenuItem affineTransform;
    private javax.swing.JToggleButton alisar;
    private javax.swing.JToggleButton amarillo1;
    private javax.swing.JButton aumento;
    private javax.swing.JToggleButton azul1;
    private javax.swing.JCheckBoxMenuItem barraEstado;
    private javax.swing.JLabel barraEstado2;
    private javax.swing.JSlider brillo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cambioEspColor;
    private javax.swing.JMenuItem colorConvertOp;
    private javax.swing.JPanel colores1;
    private javax.swing.JButton combiar;
    private javax.swing.JButton contrasteBoton;
    private javax.swing.JMenuItem convolucion;
    private javax.swing.JToggleButton cuadrado;
    private javax.swing.JButton cuadratica;
    private javax.swing.JToggleButton curva;
    private javax.swing.JToggleButton dibujoLibre;
    private javax.swing.JButton disminucion;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JButton guardar;
    private javax.swing.JButton iluminada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton lineal;
    private javax.swing.JList<Shape> listaLateral;
    private javax.swing.JMenuItem lookUpOp;
    private javax.swing.JToggleButton masColores;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JButton muestraBanda;
    private javax.swing.JToggleButton negro1;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton oscurecer;
    private javax.swing.JSplitPane panelDividido;
    private javax.swing.JMenuItem reescalado;
    private javax.swing.JCheckBox relleno2;
    private javax.swing.JToggleButton rojo1;
    private javax.swing.JButton rotar;
    private javax.swing.JToggleButton seleccion;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    private javax.swing.JToggleButton smile;
    private javax.swing.JSpinner spinner;
    private javax.swing.JToggleButton transparencia;
    private javax.swing.JToggleButton verde1;
    private javax.swing.JToggleButton volcar;
    // End of variables declaration//GEN-END:variables
}
