package practica4;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Shape;
import java.awt.event.MouseEvent;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author raul
 */
public class Lienzo extends javax.swing.JPanel {
    
    //*************DECLARACION DE VARIABLES***************//
    
    boolean relleno;
    Line2D linea;
    tipos tipo = tipos.LINEA;
    Shape forma = new Line2D.Float(0,0,0,0); 
    Color color = Color.BLACK;
    /**
     * Crearemos punto puntoInicial que será necesario para poder dibujar 
     * rectángulos y elipses
     */
    Point puntoInicial = new Point();
    
    
    //************************CONSTRUCTOR**********************//
    
    public Lienzo() {
        initComponents();
    }

    
    //*************************GETTERS AND SETTERS*************************//
    
    public tipos getTipo() {
        return tipo;
    }

    public void setTipo(tipos tipo) {
        this.tipo = tipo;
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public boolean isRelleno() {
        return relleno;
    }

    public void setRelleno(boolean relleno) {
        this.relleno = relleno;
    }

    public Line2D getLinea() {
        return linea;
    }

    public void setLinea(Line2D linea) {
        this.linea = linea;
    }

    public Shape getForma() {
        return forma;
    }

    public void setForma(Shape forma) {
        this.forma = forma;
    }

    public Point getInicial() {
        return puntoInicial;
    }

    public void setInicial(Point inicial) {
        this.puntoInicial = inicial;
    }
    
    
    //**************** MÉTODO PAINT ******************//
    
    /**
     * El metodo paint será el encargado de (solo y exclusivamente)
     * pintar la forma que tengamos.
     * No es correcto declarar objetos forma dentro ni modificarlos.
     * @param g Se le hace casting para que funcione como si fuese de Graphics2D
     */
  
    @Override
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D)g;
        g2d.setPaint(color);
        
        if(relleno){
            /**
             * No se puede hacer un fill a una linea ya que el metodo fill
             * lo que hace es pintar "lo de dentro" y no los bordes
             */
            if(this.tipo == tipos.LINEA){
                g2d.draw(forma);
            }else{
                g2d.fill(forma);
            }
        }
        
        if(!relleno){
            g2d.draw(forma);
        }
    }
    
    /**
     * Este metodo al ser invocado se encarga de dejar "la pizarra en blanco".
     * Para eso, inicializamos la forma a un objeto con coordenadas negativas.
     */
    public void nuevoLienzo(){
        forma = new Rectangle2D.Float(-1,-1,-1,-1);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        if(tipo == tipos.LINEA){
            forma = new Line2D.Float(evt.getPoint(), evt.getPoint());
        }
        
        if(tipo == tipos.ELIPSE){
            forma = new Ellipse2D.Float(evt.getPoint().x, evt.getPoint().y, 0, 0);
            puntoInicial = evt.getPoint();
        }
        
        if(tipo == tipos.RECTANGULO){
            forma = new Rectangle2D.Float(evt.getPoint().x, evt.getPoint().y, 0, 0);
            puntoInicial = evt.getPoint();
        }    
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        if(tipo == tipos.LINEA){
            ((Line2D)forma).setLine(((Line2D)forma).getP1(), evt.getPoint());
            this.repaint();
        }
        
        if(tipo == tipos.ELIPSE){
            ((Ellipse2D)forma).setFrameFromDiagonal(puntoInicial, evt.getPoint());
            this.repaint();
        }
      
        if(tipo == tipos.RECTANGULO){
            ((Rectangle2D)forma).setFrameFromDiagonal(puntoInicial, evt.getPoint());
            this.repaint();
        }
        
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
