package practica4;

import javax.swing.JFileChooser;
import java.awt.*;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.geom.Line2D;
import java.util.*;
import javax.tools.JavaFileManager;

/**
 *
 * @author raul
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     * Titulo y tamaño personalizados
     */
    public VentanaPrincipal() {
        this.setTitle("PAINT BASICO");
        this.setSize(500,500);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        negro = new javax.swing.JToggleButton();
        rojo = new javax.swing.JToggleButton();
        azul = new javax.swing.JToggleButton();
        blanco = new javax.swing.JToggleButton();
        amarillo = new javax.swing.JToggleButton();
        verde = new javax.swing.JToggleButton();
        barraEstado2 = new javax.swing.JLabel();
        relleno = new javax.swing.JCheckBox();
        lienzo2 = new practica4.Lienzo();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        linea = new javax.swing.JToggleButton();
        cuadrado = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        barraEstado = new javax.swing.JCheckBoxMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(2, 3));

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.setPreferredSize(new java.awt.Dimension(25, 25));
        negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroActionPerformed(evt);
            }
        });
        jPanel3.add(negro);

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });
        jPanel3.add(rojo);

        azul.setBackground(new java.awt.Color(0, 0, 204));
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        jPanel3.add(azul);

        blanco.setBackground(new java.awt.Color(255, 255, 255));
        blanco.setForeground(new java.awt.Color(255, 255, 255));
        blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blancoActionPerformed(evt);
            }
        });
        jPanel3.add(blanco);

        amarillo.setBackground(new java.awt.Color(255, 255, 51));
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarilloActionPerformed(evt);
            }
        });
        jPanel3.add(amarillo);

        verde.setBackground(new java.awt.Color(51, 255, 51));
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        jPanel3.add(verde);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        barraEstado2.setBackground(new java.awt.Color(153, 153, 153));
        barraEstado2.setText("Barra de Estado");
        jPanel2.add(barraEstado2, java.awt.BorderLayout.PAGE_END);

        relleno.setText("Relleno");
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        jPanel2.add(relleno, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        lienzo2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(31, 31));
        jPanel1.setMinimumSize(new java.awt.Dimension(29, 29));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);

        buttonGroup1.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/linea.png"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        jToolBar1.add(linea);

        buttonGroup1.add(cuadrado);
        cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/rectangulo.png"))); // NOI18N
        cuadrado.setFocusable(false);
        cuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadrado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoActionPerformed(evt);
            }
        });
        jToolBar1.add(cuadrado);

        buttonGroup1.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/elipse.png"))); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        jToolBar1.add(elipse);

        jPanel5.add(jToolBar1);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        Archivo.setText("Archivo");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);
        Archivo.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        jMenuBar1.add(Archivo);

        Edicion.setText("Edicion");

        barraEstado.setSelected(true);
        barraEstado.setText("Ver barra de estado");
        barraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEstadoActionPerformed(evt);
            }
        });
        Edicion.add(barraEstado);

        jMenuBar1.add(Edicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraEstadoActionPerformed

    /**
     * Muestra diálogo de abrir. 
     */
    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // muestra el cuadro de diálogo de archivos, para que el usuario pueda elegir el archivo a abrir
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        // indica cual fue la accion de usuario sobre el jfilechooser
        int resultado = selectorArchivos.showOpenDialog(this);
    }//GEN-LAST:event_AbrirActionPerformed

    /**
     * Cierra la aplicación.
     */
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @brief Pulsando nuevo borramos todos los dibujos.
     * Invoca el método nuevoLienzo de la clase lienzo que se encarga de "borrar".
     */
    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        this.lienzo2.nuevoLienzo();
    }//GEN-LAST:event_NuevoActionPerformed
    
  //*******************************CARMBIAR COLORES***************************//
    
    private void negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroActionPerformed
        this.lienzo2.setColor(Color.black);
    }//GEN-LAST:event_negroActionPerformed

    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        this.lienzo2.setTipo(tipos.ELIPSE);
    }//GEN-LAST:event_elipseActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        this.lienzo2.setTipo(tipos.LINEA);
    }//GEN-LAST:event_lineaActionPerformed

    private void cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoActionPerformed
        this.lienzo2.setTipo(tipos.RECTANGULO);
    }//GEN-LAST:event_cuadradoActionPerformed

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        this.lienzo2.setColor(Color.red);
    }//GEN-LAST:event_rojoActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        this.lienzo2.setColor(Color.blue);    }//GEN-LAST:event_azulActionPerformed

    private void blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blancoActionPerformed
        this.lienzo2.setColor(Color.white);
    }//GEN-LAST:event_blancoActionPerformed

    private void amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarilloActionPerformed
        this.lienzo2.setColor(Color.yellow);
    }//GEN-LAST:event_amarilloActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        this.lienzo2.setColor(Color.green);
    }//GEN-LAST:event_verdeActionPerformed
//*******************************************************************************//
    
    
    /**
     * @breif Se encargará de poner el relleno sabiendo si está marcado o no gracias al metodo isSelected()
     */
    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        this.lienzo2.setRelleno(relleno.isSelected());
    }//GEN-LAST:event_rellenoActionPerformed

    /**
     * Dialogo de guardar.
     * @param evt 
     */
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // muestra el cuadro de diálogo de archivos, para que el usuario pueda elegir el archivo a abrir
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        // indica cual fue la accion de usuario sobre el jfilechooser
        int resultado = selectorArchivos.showSaveDialog(this);
    }//GEN-LAST:event_GuardarActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JToggleButton amarillo;
    private javax.swing.JToggleButton azul;
    private javax.swing.JCheckBoxMenuItem barraEstado;
    private javax.swing.JLabel barraEstado2;
    private javax.swing.JToggleButton blanco;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton cuadrado;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private practica4.Lienzo lienzo2;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton negro;
    private javax.swing.JCheckBox relleno;
    private javax.swing.JToggleButton rojo;
    private javax.swing.JToggleButton verde;
    // End of variables declaration//GEN-END:variables
}
