package practica7;

import SM.RRA.IU.Lienzo2D;
import SM.RRA.IU.tipos;
import javax.swing.JFileChooser;
import java.awt.*;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.tools.JavaFileManager;

/**
 *
 * @author raul
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     * Titulo y tamaño personalizados
     */
    public VentanaPrincipal() {
        this.setTitle("PAINT BASICO");
        this.setSize(2000,2000);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barraEstado2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        nuevo = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        dibujoLibre = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        cuadrado = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        curva = new javax.swing.JToggleButton();
        smile = new javax.swing.JToggleButton();
        seleccion = new javax.swing.JToggleButton();
        colores1 = new javax.swing.JPanel();
        negro1 = new javax.swing.JToggleButton();
        rojo1 = new javax.swing.JToggleButton();
        azul1 = new javax.swing.JToggleButton();
        amarillo1 = new javax.swing.JToggleButton();
        verde1 = new javax.swing.JToggleButton();
        masColores = new javax.swing.JToggleButton();
        relleno2 = new javax.swing.JCheckBox();
        transparencia = new javax.swing.JToggleButton();
        alisar = new javax.swing.JToggleButton();
        spinner = new javax.swing.JSpinner();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        menuNuevo = new javax.swing.JMenuItem();
        Imagen = new javax.swing.JMenu();
        abreImagen = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        barraEstado = new javax.swing.JCheckBoxMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        barraEstado2.setBackground(new java.awt.Color(153, 153, 153));
        barraEstado2.setText("Barra de Estado");
        jPanel2.add(barraEstado2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setMaximumSize(new java.awt.Dimension(31, 31));
        jPanel1.setMinimumSize(new java.awt.Dimension(29, 29));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/nuevo.png"))); // NOI18N
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevo);

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/abrir.png"))); // NOI18N
        abrir.setFocusable(false);
        abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jToolBar1.add(abrir);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/guardar.png"))); // NOI18N
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jToolBar1.add(guardar);

        buttonGroup1.add(dibujoLibre);
        dibujoLibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/trazo.png"))); // NOI18N
        dibujoLibre.setFocusable(false);
        dibujoLibre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dibujoLibre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dibujoLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujoLibreActionPerformed(evt);
            }
        });
        jToolBar1.add(dibujoLibre);

        buttonGroup1.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/linea.png"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        jToolBar1.add(linea);

        buttonGroup1.add(cuadrado);
        cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/rectangulo.png"))); // NOI18N
        cuadrado.setFocusable(false);
        cuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadrado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoActionPerformed(evt);
            }
        });
        jToolBar1.add(cuadrado);

        buttonGroup1.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/elipse.png"))); // NOI18N
        elipse.setFocusable(false);
        elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elipseActionPerformed(evt);
            }
        });
        jToolBar1.add(elipse);

        buttonGroup1.add(curva);
        curva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/curva.png"))); // NOI18N
        curva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        curva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        curva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvaActionPerformed(evt);
            }
        });
        jToolBar1.add(curva);

        buttonGroup1.add(smile);
        smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/smile.png"))); // NOI18N
        smile.setFocusable(false);
        smile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        smile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smileActionPerformed(evt);
            }
        });
        jToolBar1.add(smile);

        seleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/seleccion.png"))); // NOI18N
        seleccion.setFocusable(false);
        seleccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seleccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });
        jToolBar1.add(seleccion);

        colores1.setPreferredSize(new java.awt.Dimension(35, 25));
        colores1.setLayout(new java.awt.GridLayout(2, 3));

        negro1.setBackground(new java.awt.Color(0, 0, 0));
        negro1.setPreferredSize(new java.awt.Dimension(25, 25));
        negro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro1ActionPerformed(evt);
            }
        });
        colores1.add(negro1);

        rojo1.setBackground(new java.awt.Color(255, 0, 0));
        rojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo1ActionPerformed(evt);
            }
        });
        colores1.add(rojo1);

        azul1.setBackground(new java.awt.Color(0, 0, 204));
        azul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul1ActionPerformed(evt);
            }
        });
        colores1.add(azul1);

        amarillo1.setBackground(new java.awt.Color(255, 255, 51));
        amarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo1ActionPerformed(evt);
            }
        });
        colores1.add(amarillo1);

        verde1.setBackground(new java.awt.Color(51, 255, 51));
        verde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde1ActionPerformed(evt);
            }
        });
        colores1.add(verde1);

        masColores.setText("+");
        masColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masColoresActionPerformed(evt);
            }
        });
        colores1.add(masColores);

        jToolBar1.add(colores1);

        relleno2.setBackground(new java.awt.Color(102, 255, 204));
        relleno2.setFocusable(false);
        relleno2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        relleno2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/rellenar.png"))); // NOI18N
        relleno2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        relleno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relleno2ActionPerformed(evt);
            }
        });
        jToolBar1.add(relleno2);

        transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/transparencia.png"))); // NOI18N
        transparencia.setFocusable(false);
        transparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(transparencia);

        alisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/alisar.png"))); // NOI18N
        alisar.setFocusable(false);
        alisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisarActionPerformed(evt);
            }
        });
        jToolBar1.add(alisar);

        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });
        jToolBar1.add(spinner);

        jPanel5.add(jToolBar1);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        Archivo.setText("Archivo");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);
        Archivo.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        menuNuevo.setText("Nuevo Lienzo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        Archivo.add(menuNuevo);

        jMenuBar1.add(Archivo);

        Imagen.setText("Imagen");

        abreImagen.setText("Abrir imagen");
        abreImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abreImagenActionPerformed(evt);
            }
        });
        Imagen.add(abreImagen);

        jMenuBar1.add(Imagen);

        Edicion.setText("Edicion");

        barraEstado.setSelected(true);
        barraEstado.setText("Ver barra de estado");
        barraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEstadoActionPerformed(evt);
            }
        });
        Edicion.add(barraEstado);

        jMenuBar1.add(Edicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEstadoActionPerformed
        this.barraEstado2.setVisible(barraEstado.isSelected());
    }//GEN-LAST:event_barraEstadoActionPerformed

    /**
     * Muestra diálogo de abrir. 
     */
    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImagen(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");      
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    /**
     * Cierra la aplicación.
     */
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @brief Pulsando nuevo borramos todos los dibujos.
     * Invoca el método nuevoLienzo de la clase lienzo que se encarga de "borrar".
     */
    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        this.getLienzoSeleccionado().nuevoLienzo();
    }//GEN-LAST:event_NuevoActionPerformed
    
    private void elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elipseActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setTipo(tipos.ELIPSE);
            barraEstado2.setText("Elipse");
        }
    }//GEN-LAST:event_elipseActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        if (hayLienzo()) {
            this.getLienzoSeleccionado().setTipo(tipos.LINEA);
            barraEstado2.setText("Línea");
        }
    }//GEN-LAST:event_lineaActionPerformed

    private void cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setTipo(tipos.RECTANGULO);
            barraEstado2.setText("Rectángulo");
        }
    }//GEN-LAST:event_cuadradoActionPerformed
//*******************************************************************************//
    
    
    /**
     * Dialogo de guardar.
     * @param evt 
     */
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen(true);
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                        } catch (Exception ex) {
                        System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img = new BufferedImage(300, 300, BufferedImage.TYPE_INT_RGB);
        vi.getLienzo2D().setImagen(img);
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void negro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro1ActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setColor(Color.black);
        }
    }//GEN-LAST:event_negro1ActionPerformed

    private void rojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo1ActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setColor(Color.red);
        }
    }//GEN-LAST:event_rojo1ActionPerformed

    private void azul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul1ActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setColor(Color.blue);
        }
    }//GEN-LAST:event_azul1ActionPerformed

    private void amarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo1ActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setColor(Color.yellow);
        }
    }//GEN-LAST:event_amarillo1ActionPerformed

    private void verde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde1ActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setColor(Color.green);
        }
    }//GEN-LAST:event_verde1ActionPerformed

    private void relleno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relleno2ActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setRelleno(relleno2.isSelected());
        }    
        }//GEN-LAST:event_relleno2ActionPerformed

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setMover(seleccion.isSelected());
        }    
       }//GEN-LAST:event_seleccionActionPerformed

    private void masColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masColoresActionPerformed
        if (hayLienzo()) {
            Color color = JColorChooser.showDialog(this, "Elija un color", Color.red);
            this.getLienzoSeleccionado().setColor(color);
        }
    }//GEN-LAST:event_masColoresActionPerformed

    private void curvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvaActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setTipo(tipos.CURVA);
        }
        barraEstado2.setText("Curva");
    }//GEN-LAST:event_curvaActionPerformed

    /**
     * @brief Creamos una ventana interna que se añade a nuestro escritorio y creamos
     * una imagen vacía en blanco.
     * @param evt el evento
     */
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img;
        img = new BufferedImage(800,800,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, img.getWidth(), img.getHeight());
        vi.getLienzo2D().setImagen(img);
    }//GEN-LAST:event_nuevoActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImagen(img);
                vi.setTitle(f.getName()); // Agregar esta línea para establecer el título de la ventana interna
                this.escritorio.add(vi);
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");      
            }
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImagen(true);
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                        } catch (Exception ex) {
                        System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void smileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smileActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setTipo(tipos.SMILE);
        }
        barraEstado2.setText("Smile");
    }//GEN-LAST:event_smileActionPerformed

    private void abreImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreImagenActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImagen(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");      
            }
        }
    }//GEN-LAST:event_abreImagenActionPerformed

    private void dibujoLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujoLibreActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setTipo(tipos.LIBRE);
        }
        barraEstado2.setText("Trazo libre");
    }//GEN-LAST:event_dibujoLibreActionPerformed

    private void transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setTransparente(transparencia.isSelected());
        }
    }//GEN-LAST:event_transparenciaActionPerformed

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged
        if(hayLienzo()){
            this.getLienzoSeleccionado().setGrosor(Integer.parseInt(spinner.getValue().toString()));
        }
    }//GEN-LAST:event_spinnerStateChanged

    private void alisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisarActionPerformed
        if(hayLienzo()){
            this.getLienzoSeleccionado().setLiso(alisar.isSelected());
        }
    }//GEN-LAST:event_alisarActionPerformed
   
    Lienzo2D getLienzoSeleccionado(){
        VentanaInterna vi = (VentanaInterna)escritorio.getSelectedFrame();
        return vi!=null ? vi.getLienzo2D() : null;
    }
    
    boolean hayLienzo(){
        return this.getLienzoSeleccionado() != null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenu Imagen;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem abreImagen;
    private javax.swing.JButton abrir;
    private javax.swing.JToggleButton alisar;
    private javax.swing.JToggleButton amarillo1;
    private javax.swing.JToggleButton azul1;
    private javax.swing.JCheckBoxMenuItem barraEstado;
    private javax.swing.JLabel barraEstado2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel colores1;
    private javax.swing.JToggleButton cuadrado;
    private javax.swing.JToggleButton curva;
    private javax.swing.JToggleButton dibujoLibre;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton linea;
    private javax.swing.JToggleButton masColores;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JToggleButton negro1;
    private javax.swing.JButton nuevo;
    private javax.swing.JCheckBox relleno2;
    private javax.swing.JToggleButton rojo1;
    private javax.swing.JToggleButton seleccion;
    private javax.swing.JToggleButton smile;
    private javax.swing.JSpinner spinner;
    private javax.swing.JToggleButton transparencia;
    private javax.swing.JToggleButton verde1;
    // End of variables declaration//GEN-END:variables
}
