package practica3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;

/**
 *
 * @author raul
 */
public class VentanaPrincipal extends javax.swing.JFrame implements MouseListener, MouseMotionListener {

    /**
     * Creates new form VentanaPrincipal
     */
    
    private int mouseX;
    private int mouseY;
    
    //Array de puntos donde cada posicion del primer array es 
    // un array con un conjunto de puntos
    //asi podemos hacer varias trazas que se distingan entre ellas
    private Point currentPoint;
    private ArrayList<ArrayList<Point>> points = new ArrayList<>();
    
    
    //static final int MIN_DIST = 5;
    
    public VentanaPrincipal() {
        initComponents();
        this.setSize(500, 500);
        addMouseListener(this);
        addMouseMotionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(formListener);
        addMouseListener(formListener);
        getContentPane().setLayout(new java.awt.FlowLayout());

        boton1.setText("boton1");
        boton1.addMouseMotionListener(formListener);
        boton1.addMouseListener(formListener);
        boton1.addActionListener(formListener);
        getContentPane().add(boton1);

        boton2.setText("boton2");
        boton2.addMouseListener(formListener);
        getContentPane().add(boton2);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == boton1) {
                VentanaPrincipal.this.boton1ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton1) {
                VentanaPrincipal.this.boton1MouseClicked(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == boton2) {
                VentanaPrincipal.this.boton2MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton1) {
                VentanaPrincipal.this.boton1MouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton1) {
                VentanaPrincipal.this.boton1MouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton1) {
                VentanaPrincipal.this.boton1MouseDragged(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        boton1.setBackground(Color.red);
    }//GEN-LAST:event_boton1MouseClicked

    private void boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseEntered
        boton1.setBackground(Color.blue);
    }//GEN-LAST:event_boton1MouseEntered

    private void boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseExited
        boton1.setBackground(Color.green);
    }//GEN-LAST:event_boton1MouseExited

    private void boton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1MouseDragged

    //click en ventana principal.
    //pintar
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2MouseClicked
    
    //moverse en ventana principal
    //pintar
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getX();
        int y = evt.getY();
    }//GEN-LAST:event_formMouseDragged

    
    ///////METODO DE PINTAR///////
    @Override
    public void paint(Graphics g){
        super.paint(g);
        // Dibujar todas las líneas
        for(int j = 0; j < points.size(); j++){
            if (points.get(j).size() == 1){
                Point p1 = points.get(j).get(0);
                g.fillOval(p1.x, p1.y, 10, 10);
            }
            for (int i = 0; i < points.get(j).size() -1; i++) {
                Point p1 = points.get(j).get(i);
                Point p2 = points.get(j).get(i+1);
                g.fillOval(p1.x, p1.y, 10, 10);
            }
        }
    }
    
    public void paintProfesor(Graphics g){
        super.paint(g);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    // End of variables declaration//GEN-END:variables

    ///////////////////////////////////////////////////////
    /* METODOS ABSTRACTOS SOBRECARGADOS DE LOS LISTENERS */
    ///////////////////////////////////////////////////////
    @Override
    public void mouseClicked(MouseEvent evt) {
    }

    @Override
    public void mousePressed(MouseEvent evt) {
        ArrayList<Point> current = new ArrayList<>();
        currentPoint = new Point(evt.getX(), evt.getY());
        current.add(currentPoint);
        points.add(current);
        repaint();
    }

    @Override
    public void mouseReleased(MouseEvent evt) {
        currentPoint = null;
    }

    @Override
    public void mouseEntered(MouseEvent evt) {
    }

    @Override
    public void mouseExited(MouseEvent evt) {

    }

    @Override
    public void mouseDragged(MouseEvent evt) {
       currentPoint = new Point(evt.getX(), evt.getY());
       points.get(points.size()-1).add(currentPoint);
       repaint();
        
    }

    @Override
    public void mouseMoved(MouseEvent evt) {
        mouseX = evt.getX();
        mouseY = evt.getY();
        // Volver a dibujar el panel para actualizar el punto
        repaint();
    }
}
